"""Change image_urls to image_url

Revision ID: 2f04ffbd5b47
Revises: e8924cc50ce0
Create Date: 2026-03-30 17:02:54.525482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f04ffbd5b47'
down_revision = 'e8924cc50ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_urls')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', sa.TEXT(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
