"""empty message

Revision ID: a1d2646190fc
Revises: 049836992d7d
Create Date: 2026-03-29 23:01:56.810861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d2646190fc'
down_revision = '049836992d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('background_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle', schema=None) as batch_op:
        batch_op.drop_column('background_image')
        batch_op.drop_column('background_color')

    # ### end Alembic commands ###
