"""Add image_urls column to CirclePost

Revision ID: e8924cc50ce0
Revises: f0617ebaa179
Create Date: 2026-03-30 16:42:36.818741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8924cc50ce0'
down_revision = 'f0617ebaa179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', sa.Text(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_urls')

    # ### end Alembic commands ###
