"""Add image_url field to CirclePost

Revision ID: f0617ebaa179
Revises: a1d2646190fc
Create Date: 2026-03-30 14:21:02.831772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0617ebaa179'
down_revision = 'a1d2646190fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_post', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
